.travis.scripts/test.sh, track_odometry/CMakeLists.txt, track_odometry/package.xml, track_odometry/src/tf_projection.cpp, track_odometry/src/tf_projection.hpp, track_odometry/src/tf_projection_test.cpp, track_odometry/src/track_odometry.cpp
=> track_odometry: removes projected tf output and add tf_projection node

planner_cspace/src/planner_3d.cpp
=> planner_cspace: fix distance map init timing.

planner_cspace/CMakeLists.txt, planner_cspace/package.xml, planner_cspace/src/planner_3d.cpp
=> planner_cspace: add actionlib support.

.travis.scripts/setup_docker.sh, .travis.yml
This might suppress `text file busy` error.
=> Use overlay2 as the storage driver.

planner_cspace/src/planner_3d.cpp, planner_cspace/test/data/goal_performance.yaml, planner_cspace/test/test/navigation_performance.test
The test is for comparing algorithm, not automated.
=> planner_cspace: add planning performance test.

.travis.scripts/test.sh, costmap_cspace/include/costmap_3d.h, costmap_cspace/test/src/test_costmap_3d.cpp, map_organizer/CMakeLists.txt, obj_to_pointcloud/CMakeLists.txt, planner_cspace/include/blockmem_gridmap.h, planner_cspace/src/planner_3d.cpp, safety_limiter/CMakeLists.txt
=> Suppress compile warnings and test with -Werror.

costmap_cspace/include/costmap_3d.h, costmap_cspace/include/costmap_3d_layer_base.h, costmap_cspace/include/costmap_3d_layer_footprint.h, costmap_cspace/include/costmap_3d_layer_plain.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp
also fix to use a timer instead of ros::spinOnce polling
=> costmap_cspace: make cspace template customizable

planner_cspace/test/test/navigation_rostest.test
=> planner_cspace: increase navigation test time limit

neonavigation_launch/launch/navigate.launch, planner_cspace/CMakeLists.txt, planner_cspace/include/grid_astar.h, planner_cspace/src/planner_2dof_serial_joints.cpp, planner_cspace/src/planner_3d.cpp
set `planner_cspace/num_threads (int, default: 1)` parameter to increase grid search threads
=> planner_cspace: support parallel aster search

neonavigation_launch/launch/navigate.launch, safety_limiter/CMakeLists.txt, safety_limiter/src/safety_limiter.cpp, safety_limiter/test/CMakeLists.txt, safety_limiter/test/src/test_safety_limiter.cpp, safety_limiter/test/test/safety_limiter_rostest.test
- `watchdog_interval` (double, default: `0.0` (disabled))
- `~/watchdog_reset` (std_msgs/Empty)
=> safety_limiter: add watchdog timer

planner_cspace/include/grid_astar.h, planner_cspace/src/planner_3d.cpp
also fix 3-dof astar parallelization block
=> planner_cspace: support parallel distance map search

costmap_cspace/include/costmap_3d_layer/base.h
=> costmap_cspace: clear previous position on overlay map

planner_cspace/include/bbf.h, planner_cspace/src/planner_3d.cpp
=> planner_cspace: remember costmap using binary bayes filter

planner_cspace/src/planner_3d.cpp
=> planner_cspace: fix partial costmap update with unknown cells

planner_cspace/src/planner_3d.cpp
=> planner_cspace: fix clearing remembered costmap

costmap_cspace/src/largemap_to_map.cpp, costmap_cspace/src/laserscan_to_map.cpp, costmap_cspace/src/pointcloud2_to_map.cpp, map_organizer/src/pointcloud_to_maps.cpp, map_organizer/src/save_maps.cpp, map_organizer/src/tie_maps.cpp, obj_to_pointcloud/src/obj_to_pointcloud.cpp, planner_cspace/src/dummy_robot.cpp, planner_cspace/src/patrol.cpp, planner_cspace/src/planner_2dof_serial_joints.cpp, planner_cspace/src/planner_3d.cpp, safety_limiter/src/safety_limiter.cpp
=> Fix naming styles

planner_cspace/src/planner_3d.cpp
This PR fixes cost estimation in heuristic function in A* algorithm to speed up the service.
This fix would reduce execution time ~1/2.
=> Fix cost in heuristic function for make_plan service

planner_cspace/test/src/test_abort.cpp, planner_cspace/test/src/test_preempt.cpp, planner_cspace/test/test/navigation_compat_rostest.test, planner_cspace/test/test/navigation_rostest.test
=> Reduce random test failure

planner_cspace/src/planner_3d.cpp
=> planner_cspace: fix unconverged switching back vibration

safety_limiter/src/safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter.cpp, safety_limiter/test/test/safety_limiter_compat_rostest.test, safety_limiter/test/test/safety_limiter_rostest.test
=> safety_limiter: fix safety limit logic

costmap_cspace/test/src/test_costmap_3d.cpp, planner_cspace/test/src/test_blockmem_gridmap.cpp, planner_cspace/test/src/test_blockmem_gridmap_performance.cpp, planner_cspace/test/src/test_cyclic_vec.cpp, planner_cspace/test/src/test_navigate.cpp, planner_cspace/test/src/test_preempt.cpp, track_odometry/CMakeLists.txt, track_odometry/test/src/test_tf_projection.cpp
=> Fix test names

planner_cspace/include/cyclic_vec.h, planner_cspace/include/grid_astar.h, planner_cspace/include/rotation_cache.h, planner_cspace/src/planner_2dof_serial_joints.cpp, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_cyclic_vec.cpp
* add const attributes
* use std::copysign instead of if syntax
* fix local variable names
=> planner_cspace: refactoring

planner_cspace/include/cyclic_vec.h, planner_cspace/include/motion_cache.h, planner_cspace/src/planner_3d.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/src/test_motion_cache.cpp
=> planner_cspace: split motion cache class

safety_limiter/src/safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter.cpp
merge after https://github.com/at-wat/neonavigation/pull/222
=> safety_limiter: allow escape motion from collision

trajectory_tracker/src/trajectory_tracker.cpp
=> trajectory_tracker: fix status output topic path

safety_limiter/CMakeLists.txt, safety_limiter/package.xml, safety_limiter/src/safety_limiter.cpp
This PR adds diagnostics to safety_limiter similar to the PR https://github.com/at-wat/neonavigation/pull/226 .
=> safety_limiter: add diagnostics to safety_limiter node 

planner_cspace/package.xml
=> planner_cspace: add missing test dependencies

Dockerfile.indigo, Dockerfile.kinetic, Dockerfile.lunar
=> Fix CI image caching

trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/src/test_trajectory_tracker.cpp
=> trajectory_tracker: fix angle normalization in in-place turn mode

trajectory_tracker/README.md, trajectory_tracker/src/trajectory_tracker.cpp
https://github.com/at-wat/neonavigation/pull/239#pullrequestreview-184632421
=> trajectory_tracker: add acceleration factor parameter of time optimal control

trajectory_tracker/src/trajectory_tracker.cpp
fix https://github.com/at-wat/neonavigation/pull/239/files#r242022714
=> trajectory_tracker: fix robot pose prediction

trajectory_tracker/test/src/test_trajectory_tracker.cpp, trajectory_tracker/test/test/trajectory_tracker_rostest.test
=> trajectory_tracker: add timeout to the test

trajectory_tracker/test/src/test_trajectory_tracker.cpp
=> trajectory_tracker: fix test timeout for path with velocity

.post-release/Dockerfile, .post-release/README.md, .post-release/docker-compose.yml, .post-release/post-release-test.sh, .post-release/test.sh
=> Add post-release test script

safety_limiter/CMakeLists.txt, safety_limiter/package.xml
=> safety_limiter: fix package dependencies

neonavigation_launch/config/navigate.yaml, planner_cspace/test/test/actionlib_common_rostest.test, planner_cspace/test/test/navigation_compat_rostest.test, planner_cspace/test/test/navigation_rostest.test, trajectory_tracker/README.md, trajectory_tracker/src/trajectory_tracker.cpp
=> trajectory_tracker: remove unused parameters

trajectory_tracker/README.md, trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/src/test_trajectory_tracker.cpp, trajectory_tracker/test/test/trajectory_tracker_rostest.test
=> trajectory_tracker: linear velocity adaptive gain control

trajectory_tracker/CMakeLists.txt, trajectory_tracker/test/CMakeLists.txt, trajectory_tracker/test/src/test_trajectory_tracker.cpp, trajectory_tracker/test/test/trajectory_tracker_rostest.test
=> trajectory_tracker: speed up simulation on rostest

track_odometry/src/tf_projection_node.cpp, track_odometry/test/src/test_tf_projection_node.cpp, track_odometry/test/test/tf_projection_rostest.test
=> track_odometry: add project_posture option to tf_projection node

track_odometry/src/track_odometry.cpp, track_odometry/test/src/test_track_odometry.cpp, track_odometry/test/test/track_odometry_rostest.test
=> track_odometry: fix z_filter unit to seconds

planner_cspace/include/planner_cspace/planner_3d/grid_metric_converter.h, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_grid_metric_converter.cpp
fix #293 
holding until kinetic post-release testing
=> planner_cspace: fix path cost calculation and interpolation

planner_cspace/src/planner_3d.cpp
https://github.com/at-wat/neonavigation/pull/304/files#r287356571
=> planner_cspace: revert default sw_wait parameter

safety_limiter/src/safety_limiter.cpp
This PR fixes footprint radius calculation bug.
=> safety_limiter: fix footprint radius calculation

planner_cspace/src/planner_3d.cpp
fixes https://github.com/at-wat/neonavigation/issues/324
=> planner_cspace: reject request if input frame are located at diffrent frame to the map

planner_cspace/README.md, planner_cspace/src/planner_3d.cpp
use `~/remembered` topic instead
---
fix #281
=> planner_cspace: remove hist mode of debug output

neonavigation_launch/config/navigate.yaml, neonavigation_launch/launch/demo.launch, trajectory_tracker/src/trajectory_tracker.cpp
Original parameter was quite bad at control characteristic and path following was almost done by stop-and-rotate mode.
This PR adds info message on stop-and-rotate mode and update the parameters in demo launch.
=> trajectory_tracker: update demo params

planner_cspace/test/src/test_navigate.cpp
may `fix` https://github.com/at-wat/neonavigation/issues/344 (1)
=> planner_cspace: latch publish data in navigation test

costmap_cspace/include/costmap_cspace/costmap_3d_layer/output.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/stop_propagation.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp
=> costmap_cspace: fix costmap output for out-of-boundary overlay map

costmap_cspace/include/costmap_cspace/costmap_3d_layer/base.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/output.h
=> costmap_cspace: fix memory corruption

safety_limiter/README.md, safety_limiter/src/safety_limiter.cpp
=> safety_limiter: remove debug output

joystick_interrupt/src/joystick_interrupt.cpp
=> joystick_interrupt: publish twist soon after simulator starts

planner_cspace/CMakeLists.txt, planner_cspace/include/planner_cspace/blockmem_gridmap.h, planner_cspace/include/planner_cspace/planner_3d/costmap_bbf.h, planner_cspace/src/costmap_bbf.cpp, planner_cspace/src/planner_3d.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/src/test_costmap_bbf.cpp
=> planner_cspace: fix remember_updates feature

.travis/test.sh, trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/src/test_trajectory_tracker.cpp, trajectory_tracker/test/test/trajectory_tracker_rostest.test
=> trajectory_tracker: fix test stability

track_odometry/test/src/test_track_odometry.cpp
Wait receiving all resultant message.
=> track_odometry: fix test stability

.travis.yml, .travis/test.sh, codecov.yml
* Concurrently run tests
* Remove coverage-only build
=> Update CI setting

safety_limiter/CMakeLists.txt, safety_limiter/package.xml, safety_limiter/src/safety_limiter.cpp, safety_limiter/test/include/test_safety_limiter_base.h, safety_limiter/test/src/test_safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter2.cpp, safety_limiter/test/test/safety_limiter_rostest.test
=> safety_limiter: use fixed frame for accumulating input cloud

trajectory_tracker/test/src/test_trajectory_tracker.cpp
=> trajectory_tracker: fix test initialization timeout

planner_cspace/package.xml, trajectory_tracker/package.xml
planner_cspace_msgs >= 0.7.0
trajectory_tracker_msgs >= 0.8.0
=> Add message package version constraints

map_organizer/CMakeLists.txt, obj_to_pointcloud/CMakeLists.txt, safety_limiter/CMakeLists.txt
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894656
Seems already been fixed by 1.8.0+dfsg1-4.
=> Remove old workaround for debian stretch build

map_organizer/CMakeLists.txt, obj_to_pointcloud/CMakeLists.txt, safety_limiter/CMakeLists.txt
This reverts commit e3829b5cb2cab41ef8db6ecb377d2cd7d1651356.
fix #477
=> Revert "Remove old workaround for debian stretch build (#473)"

planner_cspace/include/planner_cspace/cyclic_vec.h
=> planner_cspace: fix uninitialized variable

planner_cspace/src/planner_3d.cpp
fix #468 
(not performance critical calculation)
=> planner_cspace: simplify path switch detection condition

planner_cspace/test/src/test_navigate.cpp
=> planner_cspace: add wait to navigation tests

joystick_interrupt/src/joystick_mux.cpp
=> joystick_interrupt: validate joystick button array size in joystick_mux

planner_cspace/test/src/test_navigate.cpp
To invoke map update callback.
=> planner_cspace: periodically update local map in the test

trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/CMakeLists.txt, trajectory_tracker/test/include/trajectory_tracker_test.h, trajectory_tracker/test/src/test_trajectory_tracker.cpp, trajectory_tracker/test/test/trajectory_tracker_frame_rate_rostest.test, trajectory_tracker/test/test/trajectory_tracker_rostest.test
=> trajectory_tracker: predict odometry by extrapolation

trajectory_tracker/README.md, trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/CMakeLists.txt, trajectory_tracker/test/src/test_trajectory_tracker_with_odom.cpp, trajectory_tracker/test/test/trajectory_tracker_rostest.test, trajectory_tracker/test/test/trajectory_tracker_with_odom_rostest.test
=> trajectory_tracker: add odometry timeout checking

joystick_interrupt/test/src/test_joystick_interrupt.cpp, track_odometry/test/src/test_track_odometry.cpp, trajectory_tracker/test/include/trajectory_tracker_test.h
=> Increase initialization timeout in the tests

trajectory_tracker/src/trajectory_tracker.cpp
As path_step_done_ is set to 0 when a new path is received, path tracking is performed against a wrong target once.
In this log, `nearest` should be always 1 as the robot is turning in place toward the goal.
However it became 0 at the selected frame. This is because a new path was received just before that frame.
This change separates the path tracking algorithm from `control()`, and the velocity control algorithm is remained in it.
After a new path is received, the tracking algorithm is called to update `path_step_done_` parameter.
=> trajectory_tracker: fix wrong tracking target just after new path is received

planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_navigate.cpp
This PR enables to apply tolerance in "make_plan" service. 
The tolerance value designated in nav_msgs::GetPlanRequest is used instead of "tolerance_range" parameter.
=> planner_cspace: enable tolerance in make_plan

costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp, planner_cspace/include/planner_cspace/bbf.h, planner_cspace/include/planner_cspace/grid_astar.h, planner_cspace/src/motion_cache.cpp, planner_cspace/src/planner_2dof_serial_joints.cpp, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_blockmem_gridmap_performance.cpp, planner_cspace/test/src/test_costmap_bbf.cpp, planner_cspace/test/src/test_cyclic_vec.cpp, planner_cspace/test/src/test_debug_outputs.cpp, planner_cspace/test/src/test_grid_metric_converter.cpp, planner_cspace/test/src/test_motion_cache.cpp, planner_cspace/test/src/test_motion_primitive_builder.cpp, safety_limiter/src/safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter2.cpp, trajectory_tracker/test/src/test_trajectory_recorder.cpp, trajectory_tracker/test/src/test_trajectory_tracker.cpp
Refs https://github.com/seqsense/ros_style/pull/14
=> Apply clang-format-11 with new setting

planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_costmap_watchdog.cpp
=> planner_cspace: recover error on FINISHING state

planner_cspace/src/planner_3d.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/src/test_planner_3d_map_size.cpp, planner_cspace/test/test/planner_3d_map_size_rostest.test
=> planner_cspace: fix access violation on wrong size costmap_update message

planner_cspace/test/CMakeLists.txt, planner_cspace/test/include/planner_cspace/action_test_base.h, planner_cspace/test/src/test_abort.cpp, planner_cspace/test/src/test_preempt.cpp, planner_cspace/test/src/test_tolerant_action.cpp
https://github.com/at-wat/neonavigation/issues/655#issue-1512417216
Failed with `Goal [map] pose must be in the map frame [].` when action is requested before map load.
Check navigation availability before test.
=> planner_cspace: fix flaky action tests

planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_navigate.cpp
Set `PATH_NOT_FOUND` error status if goal or robot is in rock on updating goal
=> planner_cspace: fix status when goal or robot is in rock on updating goal

.github/workflows/test.yaml, planner_cspace/test/src/test_navigate.cpp, planner_cspace/test/test/navigation_compat_rostest.test, planner_cspace/test/test/navigation_remember_rostest.test, planner_cspace/test/test/navigation_rostest.test
- tweak trajectory_tracker parameter
- use default switch back wait duration
- fix parameterized rostest result
- wait topics on init
- fix local map publish timing on stuck tests
=> planner_cspace: fix flaky navigation tests
