at-wat/neonavigation

track_odometry/src/track_odometry.cpp
This assumes transform between imu and base_link is static.
=> track_odometry: uses latest transform between imu and base_link

README.md, costmap_cspace/README.md, map_organizer/README.md, neonavigation_launch/README.md, obj_to_pointcloud/README.md, planner_cspace/README.md, safety_limiter/README.md, track_odometry/README.md, trajectory_tracker/README.md
=> Add READMEs.

.travis.scripts/test.sh
This might avoid `text file busy` error in docker.
=> Add sync command to test script.

safety_limiter/src/safety_limiter.cpp
=> safety_limiter: avoid kdtree build for empty cloud.

planner_cspace/src/planner_3d.cpp
Fill `header.frame_id` of the path messages without poses.
=> Fix header of empty path.

.travis.scripts/test.sh
Navigation simulation test randomly timed out
due to the load increase of the travis-ci.
This commit adds -O2 to speed up planning on tests.
=> Enable optimization of the CI builds.

planner_cspace/include/blockmem_gridmap.h, planner_cspace/src/planner_3d.cpp
* Check that given goal is on the map.
fixes #89
=> planner_cspace: validate goal position.

costmap_cspace/include/costmap_3d_layer_base.h, costmap_cspace/include/costmap_3d_layer_footprint.h, costmap_cspace/include/costmap_3d_layer_plain.h, costmap_cspace/include/cspace3_cache.h, costmap_cspace/include/polygon.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp
=> costmap_cspace: refactor costmap layer classes

costmap_cspace/include/costmap_3d_layer/base.h, costmap_cspace/src/costmap_3d.cpp
If an overlay map arrives before a root map, overlay map was ignored
since frame_id of the root map is not yet given.
The commit enables to always store overlay map and keep until receiving
the root map.
=> costmap_cspace: always store received overlay map

planner_cspace/src/dummy_robot.cpp
Fixes #144 
This PR uses TF from frame_id of incoming message to base_link to estimate initial robot pose(odom to base_link).
=> planner_cspace: use frame_id of incoming message to set dummy robot pose

map_organizer/CMakeLists.txt, obj_to_pointcloud/CMakeLists.txt, safety_limiter/CMakeLists.txt
Binary installed pcl provided by Linux distro is built with -march=native
which causes a lot of compatibility problems.
Define PCL_NO_PRECOMPILE to disable using the binary version.
ref: https://github.com/at-wat/mcl_3dl/pull/161
=> Compile with PCL_NO_PRECOMPILE

safety_limiter/src/safety_limiter.cpp
previous implementation estimates collision distance bit larger than actual.
=> safety_limiter: fix first time step of collision prediction

planner_cspace/CMakeLists.txt, planner_cspace/package.xml, planner_cspace/src/planner_3d.cpp
This PR adds diagnostic_updater to publish /diagnostics topic periodically.
As far as I know, the planner status is composed to /planner/status topic, so the updater checks only the topic.
The output of  `rostopic echo /diagnostics` 
e.g.
- going well
```
---
header: 
seq: 432
stamp: 
secs: 1538448072
nsecs:  44865701
frame_id: ''
status: 
- 
level: 0
name: "planner_3d: Status"
message: "Going well."
hardware_id: "none"
values: 
- 
key: "status"
value: "1"
- 
key: "error"
value: "0"
---
```
- path not found
```
---
header: 
seq: 103
stamp: 
secs: 1538447857
nsecs: 596350716
frame_id: ''
status: 
- 
level: 2
name: "planner_3d: Status"
message: "Path not found."
hardware_id: "none"
values: 
- 
key: "status"
value: "1"
- 
key: "error"
value: "2"
---
```
=> planner_cspace: add diagnostics to planner node

trajectory_tracker/test/src/test_trajectory_tracker.cpp
```
[ROSTEST]-----------------------------------------------------------------------
[trajectory_tracker.rosunit-test_trajectory_tracker/StraightStop][passed]
[trajectory_tracker.rosunit-test_trajectory_tracker/StraightVelocityChange][passed]
[trajectory_tracker.rosunit-test_trajectory_tracker/CurveFollow][passed]
[trajectory_tracker.rosunit-test_trajectory_tracker/InPlaceTurn][FAILURE]-------
/catkin_ws/src/neonavigation/trajectory_tracker/test/src/test_trajectory_tracker.cpp:334
Expected: (cmd_vel_->angular.z * ang) > (0), actual: -4.54747e-14 vs 0
--------------------------------------------------------------------------------
```
=> trajectory_tracker: add tolerance to InPlaceTurn

track_odometry/src/tf_projection.cpp, track_odometry/test/CMakeLists.txt, track_odometry/test/src/test_tf_projection_node.cpp, track_odometry/test/test/tf_projection_rostest.test
Set missing `child_frame_id` field in `geometry_msgs::TransformStamped`.
This line was incorrectly deleted in the TF2 migration commit. https://github.com/at-wat/neonavigation/commit/daa67739c2428359f3276098379a1c3ef91a8fa2
=> track_odometry: set missing child_frame_id in tf_projection

planner_cspace/src/planner_3d.cpp
fix #287 
I'm not sure this could happen in real use cases, but better to have.
=> planner_cspace: limit negative cost to avoid infinite search loop

safety_limiter/src/safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter.cpp
This PR fixes possibility to be collided to obstacle if the robot moves to backward.
Internally, If the robot moves to backward(`twist_.linear.x < 0`) and rotates ~~counter~~ clockwise(`twist_.angular.z < 0`), the following line would be false, then robot will not limit velocity even if obstacle is placed behind the robot.
https://github.com/at-wat/neonavigation/blob/master/safety_limiter/src/safety_limiter.cpp#L423
This PR fixes `*_escape_remain` value that should be negative regardless of robot velocity, except if the robot is already collided.
=> safety_limiter: fix backward motion limit

safety_limiter/test/src/test_safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter2.cpp
Simulation based safety_limiter test exceeds threshold a little bit on ROS official buildfarm.
It might be caused by the huge amount of resuming jobs stored during buildfarm outage.
The error can be reproduced locally by running benchmark software occupying 100% of CPU during rostest.
=> safety_limiter: increase simulation test publish rate

planner_cspace/src/planner_3d.cpp
This PR make a robot stop immediately after path planning completed; succeeded or aborted.
Without this, the robot may still rotate for a while until [next loop](https://github.com/at-wat/neonavigation/blob/master/planner_cspace/src/planner_3d.cpp#L1290).
e.g. rotates at least 0.25 sec. by the default parameter `freq=4Hz`).
=> planner_cspace: publish empty path immediately after planning aborted

planner_cspace/include/planner_cspace/grid_astar.h, planner_cspace/test/src/test_grid_astar.cpp
`GridAstar::findPath` is called on search timeout to pass the progress result to `cbProgress`.
findPath must be const member to guarantee it never breaks intermediate search state.
---
fix #356 
like:
=> planner_cspace: fix incomplete output path after search timeout

track_odometry/CMakeLists.txt, track_odometry/package.xml, track_odometry/src/track_odometry.cpp, track_odometry/test/src/test_track_odometry.cpp
=> track_odometry: synchronize Odometry and IMU

planner_cspace/include/planner_cspace/blockmem_gridmap.h, planner_cspace/test/src/test_blockmem_gridmap.cpp
=> planner_cspace: fix debug build compatibility

planner_cspace/src/planner_3d.cpp
fix #311
- speed-up replanning against moving obstacle
- avoid to generate a path close to the moving obstacle
=> planner_cspace: clear hysteresis if new obstacle is on the previous path

trajectory_tracker/include/trajectory_tracker/path2d.h, trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/src/test_trajectory_tracker.cpp
Paths end with interpolated rotation were not correctly tracked.
e.g. tracking a following path stopped before reaching final pose.
- x: 0, y: 0, yaw: 0
- x: 1, y: 0, yaw: 0
- x: 2, y: 0, yaw: 0 (stopped here)
- x: 2, y: 0, yaw: 1
- x: 2, y: 0, yaw: 2
- x: 2, y: 0, yaw: 3
=> trajectory_tracker: track interpolated rotation

neonavigation_launch/config/navigate.yaml, neonavigation_launch/config/visualization.rviz, neonavigation_launch/launch/demo.launch, planner_cspace/src/planner_3d.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/data/goal_debug_outputs.yaml, planner_cspace/test/src/test_debug_outputs.cpp, planner_cspace/test/test/debug_outputs_rostest.test
=> planner_cspace: publish internally used maps as OccupancyGrid

planner_cspace/CMakeLists.txt, planner_cspace/include/planner_cspace/planner_3d/grid_astar_model.h, planner_cspace/include/planner_cspace/planner_3d/motion_primitive_builder.h, planner_cspace/src/grid_astar_model_3dof.cpp, planner_cspace/src/motion_primitive_builder.cpp, planner_cspace/src/planner_3d.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/src/test_motion_primitive_builder.cpp, planner_cspace/test/src/test_planner_3d_cost.cpp
Instead of whole search_list, only followable moving primitives are remained in A* algorithm.
This PR can reduce calculation time significantly.
The following performance comparisons are performed using our simulator.
Times are obtained from messages shown by L1547 of planner_3d.cpp.
Average time while 3-dof planning: 
master: 0.3514 sec.
This PR: 0.0520 sec.
Worst time: 
master: 0.9421 sec.
This PR: 0.1582 sec.
=> planner_cspace: implement motion primitive algorithm for speed-up

trajectory_tracker/include/trajectory_tracker/path2d.h, trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/src/test_path2d.cpp
The current trajectory_tracker uses 3 points to calculate curvature.
Thus, when the last motion primitive of the path is a curve, it cannot calculate its curvature.
This causes path tracking failures even in gazebo simulator.
With this PR, it can calculate the curvature of the last motion primitive using the logic same as planner_cspace::planner_3d::RotationCache.
The "planned_path" in the following results consists of consecutive single motion primitive (x: 0.3[m], y: 0.1[m], yaw, PI/4[rad], curvature: 2.426)
master branch (gazebo simulator):
orange: planned path, pink: actual path
The robot could not track the path and stopped as the distance between the path and the robot became more than 0.1m.
This PR (gazebo simulator):
The robot successfully reached the goal.
This PR (actual robot) …
=> trajectory_tracker: calculate correct curvature at the end of path

trajectory_tracker/src/trajectory_tracker.cpp
path_header is useful to check correspondence between path and status.
=> trajectory_tracker: add path header to TrajectoryTrackerStatus

planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_abort.cpp, planner_cspace/test/src/test_costmap_watchdog.cpp, planner_cspace/test/src/test_navigate_boundary.cpp
By this PR, robot can stop immediately when path is blocked by moving objects even during sw_wait.
=> planner_cspace: replan immediately when path is blocked by new obstacles

planner_cspace/src/planner_3d.cpp
The priority of `?` operator is lower than `<` operator, so this if-clause always returned true.
=> planner_cspace: fix condition of planning finish

track_odometry/src/track_odometry.cpp
Refs #216
In some situations, latency of subscribers becomes large without tcpNoDelay option.
https://qiita.com/kiy_at_dev/items/1e2ae8bfa400f12e1066
=> track_odometry: Add enable_tcp_no_delay option to reduce latency

track_odometry/test/src/test_tf_projection_node.cpp
=> track_odometry: increase transform timeout in tests

planner_cspace/include/planner_cspace/jump_detector.h, planner_cspace/test/src/test_navigate_boundary.cpp, track_odometry/src/tf_projection_node.cpp, trajectory_tracker/test/src/test_trajectory_tracker.cpp
which causes huge amount of warnings on geometry2 0.7.1
fix #495
=> Fix duplicated tf timestamp

.rosinstall
there is no build dependency with neonavigation_rviz_plugins
=> Remove rviz_plugins from .rosinstall

safety_limiter/test/CMakeLists.txt
During a prerelease test I saw a build error when building tests for `safety_limiter`
```
[ 20%] Built target nodelet_generate_messages_py
[ 40%] Built target safety_limiter
Scanning dependencies of target test_safety_limiter2
[ 50%] Building CXX object test/CMakeFiles/test_safety_limiter2.dir/src/test_safety_limiter2.cpp.o
In file included from /tmp/ws_overlay/src/safety_limiter/test/src/test_safety_limiter2.cpp:39:
/tmp/ws_overlay/src/safety_limiter/test/include/test_safety_limiter_base.h:43:10: fatal error: tf2_geometry_msgs/tf2_geometry_msgs.h: No such file or directory
43 | #include <tf2_geometry_msgs/tf2_geometry_msgs.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [test/CMakeFiles/test_safety_limiter2.dir/build.make:63: …
```
=> [Noetic] Add missing includes and libraries

planner_cspace/src/planner_3d.cpp
Currently, too many warning messages are displayed until planner_3d receives the first costmap.
=> planner_cspace: avoid showing too many warning messages

joystick_interrupt/src/joystick_interrupt.cpp, joystick_interrupt/test/src/test_joystick_interrupt.cpp
- When the interrupt button is released, no new twist were published.
Systems relying on the most recent twist could potentially continue
executing a non zero twist even if the interrupt button has been released.
- Send a zero twist when the interrupt button was pressed and is released.
=> joystick_interrupt: send zero twist when interrupt button is released

trajectory_tracker/CMakeLists.txt, trajectory_tracker/cfg/TrajectoryTracker.cfg, trajectory_tracker/package.xml, trajectory_tracker/src/trajectory_tracker.cpp
By this PR, parameters of trajectory_tracker can be changed while the node is running using dynamic_reconfigure.
It makes easy to adjust parameters.
=> trajectory_tracker: make trajectory_tracker dynamic-reconfigurable

trajectory_tracker/src/trajectory_tracker.cpp
Trajectory tracker status was changed to GOAL before actually arriving the goal due to prediction.
Determine goal if both predicted and raw pose is in the tolerance.
fix #539
=> trajectory_tracker: goal if both raw and predicted pose is in tolerance

planner_cspace/src/planner_3d.cpp
When "Goal is in Rock", an empty path and a path including only the goal pose are published alternately as follows.
```
---
header: 
seq: 28301
stamp: 
secs: 7080
nsecs:   8000000
frame_id: "map"
poses: []
---
header: 
seq: 28302
stamp: 
secs: 7080
nsecs: 502000000
frame_id: "map"
poses: 
- 
header: 
seq: 3
stamp: 
secs: 7080
nsecs: 502000000
frame_id: "map"
pose: 
position: 
x: -2.69430923462
y: 13.590215683
z: 0.0
orientation: 
x: 0.0
y: 0.0
z: 0.702808114546
w: 0.711379472665
---
header: 
seq: 28303
stamp: 
secs: 7081
nsecs:   9000000
frame_id: "map"
poses: []
---
header: 
seq: 28304
stamp: 
secs: 7081
nsecs: 511000000
frame_id: "map"
poses: 
- 
header: 
seq: 3
stamp: 
secs: 7081
nsecs: 511000000
frame_id: "map"
pose: 
position: 
x: -2.69430923462
y: 13.590215683
z: 0.0
orientation: …
```
=> planner_cspace: avoid publishing invalid path when escaping

costmap_cspace/src/laserscan_to_map.cpp
`LaserscanToMapNode` has `z_min_` and `z_max_` params as well as `Pointcloud2ToMapNode`.
However, `LaserscanToMapNode` never use it.
Therefore, I added the function to remove out of z range objects as in `Pointcloud2ToMapNode`.
=> costmap_cspace: enable func to remove objects out of z range

costmap_cspace/include/costmap_cspace/costmap_3d_layer/footprint.h
- Raw pointers are used to get cost values without overheads.
- If-clauses are removed by using x and y ranges calculated in advance.
- CPU usage of costmap_cspace was reduced from about 75% to about 40% on our robots.
=> costmap_cspace: make Costmap3dLayerFootprint::generateCSpace faster

costmap_cspace/include/costmap_cspace/costmap_3d_layer/base.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/footprint.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/output.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/plain.h, costmap_cspace/test/src/test_costmap_3d.cpp
Costmap3dLayerPlain: As each map does not vary with its yaw angle, only first map is generated and copied to others.
Costmap3dLayerOutput: When an entire map is updated, all memories are copied at once. Otherwise, each raster is copied.
=> costmap_cspace: make Costmap3dLayerPlain and Costmap3dLayerOutput faster

planner_cspace/src/planner_3d.cpp
`cm_hyst_.clear(100);` sets the value to the whole array in `cm_hyst_`.
Especially when the map is large. it spends too much time.
This PR reduces the processing time of the clearing method by restoring only changed cells.
=> planner_cspace: improve performance of hysteresis clearing

planner_cspace/include/planner_cspace/blockmem_gridmap.h, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_blockmem_gridmap.cpp
When the map is large, resetting of `cm_`, `cm_rough_` , and `cm_updates_` spends too much calculation time as it overwrites all cells in arrays of them. 
In this PR, they are partially reset using ranges of the previous local map.
When the size of map is 5000 x 3000, processing times are reduced from more than 200ms to less than 10ms.
=> planner_cspace: improve performance of costmap reset

planner_cspace/src/planner_3d.cpp
If planned path has a swtich back and the path is collided with obstacles in updated cost map, replanning is immediately performed even if `next_replan_time` has not passed. In such a case, `sw_wait` is errorneously added to `next_replan_time` in each replanning and `next_replan_time` can be very long time.
By this PR, `next_replan_time` is reset after each `waitUntil()` to avoid the problem.
=> planner_cspace: reset next_replan_time after waitUntil()

costmap_cspace/include/costmap_cspace/pointcloud_accumulator.h, costmap_cspace/src/laserscan_to_map.cpp, costmap_cspace/src/pointcloud2_to_map.cpp, costmap_cspace/test/CMakeLists.txt, costmap_cspace/test/src/test_pointcloud_accumulator.cpp
The main purpose of this PR is to fix a typo in the `PointcloudAccumurator` class name. As this might break code relying on this class outside of this repository, I kept the original available. Maybe it can be completely removed when releasing the next major version. I also added some tests for the `PointcloudAccumulator` methods.
=> Rename PointcloudAccumurator to PointcloudAccumulator

trajectory_tracker/test/src/test_trajectory_tracker.cpp
SwitchBackWithPathUpdate has 1.5 times longer path than the other test cases.
=> trajectory_tracker: increase SwitchBackWithPathUpdate test timeout

planner_cspace/src/planner_3d.cpp
The `frame_id` of finish path should be the same as that of `goal_`.
=> planner_cspace: Fix header of finish path

costmap_cspace/include/costmap_cspace/costmap_3d_layer/output.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/src/costmap_3d_layers.cpp, costmap_cspace/test/src/test_costmap_3d.cpp
This PR divides Costmap3dLayerOutput into Costmap3dStaticLayerOutput and Costmap3dUpdateLayerOutput.
This change can omit unnecessary generation of costmap_cspace_msgs::CSpace3DUpdate when static map is updated.
=> Divide output layer class into specific classes

costmap_cspace/include/costmap_cspace/costmap_3d_layer/plain.h, costmap_cspace/test/src/test_costmap_3d.cpp
The overloaded `Costmap3dLayerPlain::generateCSpace` works correctly only when the maps of its parent layer are same for all angles.
This PR removes it and use the original method.
=> Fix Costmap3dLayerPlain when its parent is not plain

joystick_interrupt/src/joystick_interrupt.cpp, joystick_interrupt/test/src/test_joystick_interrupt.cpp, joystick_interrupt/test/test/joystick_interrupt_rostest.test
When `linear_y_vel` and `linear_y_axis` are set, joystick_interrupt publishes y-directional velocities.
=> joystick_interrupt: enable omni-directional movement

planner_cspace/src/path_interpolator.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/src/test_path_interpolator.cpp
Output path might contain duplicated poses due to interpolation logic and quantization error.
=> planner_cspace: fix pose duplication on path interpolation

safety_limiter/src/safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter2.cpp, safety_limiter/test/test/safety_limiter2_rostest.test
If (`twist_` * `dt_`) exceeds `*_margin_`, the robot may not be able to stop further from the collision point than `*_margin_`. I think that this is because `*_col_` is the "collision position", but this should be a "one step away from collision position".
In this PR,
- `twist_` * `dt_` is subtracted from `*_col` when `colliding==true`.
- Acceleration is considered in `test_safety_limiter2`.
- Parameters for the test are adjusted.
- With these parameters, the `master` (sometimes) fails when `vel` == -0.8 or 0.8 in the test.
Failure case with `master` on my local environment.
```
[ROSTEST]-----------------------------------------------------------------------
[safety_limiter.rosunit-test_safety_limiter2/SafetyLimitLinearSimpleSimulationWithMargin][FAILURE] …
```
=> safety_limiter: make sure to keep margin from obstacles

safety_limiter/test/src/test_safety_limiter.cpp, safety_limiter/test/src/test_safety_limiter2.cpp
https://github.com/at-wat/neonavigation/issues/655#issuecomment-1366472064
Continue simulation for a bit after the speed gets small.
=> safety_limiter: fix flaky simulation tests

planner_cspace/include/planner_cspace/blockmem_gridmap.h, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_blockmem_gridmap.cpp
- Fix memory access violation
- Fix map_update_max to contain upper boundary edge pixels
Word definitions:
- max: contains the value
- size: does not contain the value
---
Fix #671 
Running related tests multiple times at https://github.com/at-wat/neonavigation/pull/666 and segmentation fault is not occurred.
=> planner_cspace: fix map update range

planner_cspace/include/planner_cspace/planner_3d/distance_map.h, planner_cspace/src/distance_map.cpp, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_distance_map.cpp
Fix uninitialized variables detected by `valgrind` on gtest executables.
=> planner_cspace: fix uninitialized variables in DistanceMap

planner_cspace/test/include/planner_cspace/action_test_base.h
=> planner_cspace: fix string template constexpr in test

costmap_cspace/include/costmap_cspace/costmap_3d_layer/base.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp
This argument is implemented so as to be able to toggle updateChainEntry() only after all map layers have been processed within SQ Maps.
=> costmap_cspace: added update_chain_entry bool arguement to processMapOverlay function

planner_cspace/src/patrol.cpp, planner_cspace/src/planner_3d.cpp, planner_cspace/test/CMakeLists.txt, planner_cspace/test/src/test_navigate.cpp
In the current master branch, When `cnt_stuck_` has a positive value, `status.error` becomes `PATH_NOT_FOUND`.  The value of `cnt_stuck_` is incremented when the start or the goal cell is occupied, and it is retained even after the occupied cell is cleared and path planning is succeeded. Therefore, the `status.error` never returns to `GOING_WELL` in such cases. In addition, when the start cell is occupied, `status.error` should become `IN_ROCK`.
This bug is introduced by https://github.com/at-wat/neonavigation/commit/db2532967d0e15f85e7ee8657183abddcb1719ea.
In this PR, `cost_estim_cache_created_` is used to check if the start or goal cell is occupied instead of `cnt_stuck_`.
In addition, `is_start_occupied_` flag is added to distinguish `IN_ROCK` status.
Some inappropriate names of …
=> planner_cspace: fix error status handling after cost_estim_cache_ was not created

planner_cspace/src/planner_3d.cpp
`relocateDiscretePoseIfNeeded()` is currently applied to a grid coordinate converted from `goal_`, and `goal_` is updated using the relocated grid coordinate. As `createCostEstimCache()` is called repeatedly, `goal_` can be relocated multiple times.
=> planner_cspace: avoid multiple goal pose relocation

planner_cspace/src/distance_map.cpp, planner_cspace/test/src/test_distance_map.cpp
Test result without the fix:
```
[ RUN      ] DistanceMapTest.StartOutOfMap
[ INFO] [1692768470.380405208]: x:3, y:3 grids around the boundary is ignored on path search
Segmentation fault
-- run_tests.py: verify result "/sq_ws/build/test_results/planner_cspace/gtest-test_distance_map.xml"
Cannot find results, writing failure results to '/sq_ws/build/test_results/planner_cspace/MISSING-gtest-test_distance_map.xml'
```
=> planner_space: fix segmentation fault on out-of-map

planner_cspace/src/planner_3d.cpp
The algorithms to build path planning start poses are moved to a new function `buildStartPoses()`.
This const function returns the status of the start pose and builds a vector of start poses. 
In addition, the algorithm is fixed to check the finishing condition when the start pose is relocated.
=> planner_cspace: refactor start pose building algorithm and fix finishing condition when start is relocated

costmap_cspace/README.md, costmap_cspace/include/costmap_cspace/costmap_3d_layer/footprint.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/plain.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp
`linear_spread_min_cost` is the cost of edge grids spread from an occupied grid. (See Costmap3dLayerOutput.LinearSpreadMinCost)
This parameter can make the costs of grids near obstacles higher to avoid other costs such as preferences overriding the costs of these grids.
=> costmap_cspace: add linear_spread_min_cost parameter

planner_cspace/src/grid_astar_model_3dof.cpp, planner_cspace/test/src/test_planner_3d_cost.cpp
This PR fixes a bug in `GridAstarModel3D::cost()`.
When the movement between `cur` and `next` is an in-place turning, `cm_[cur]` is not evaluated. I think it is a simple mistake.
In contrast, when the movement between `cur` and `next` is not an in-place turning, `MotionCache` is used to interpolate the movement of the robot. Because `MotionCache::Page::getMotion()` does not return the last pose (I guess this is needed to avoid double counting of costs), the `cm_[next]` is not evaluated. Therefore, when only the `cm_[next]` is 100 and the costs of other poses are not 100, `GridAstarModel3D::cost()` returns a positive value mistakenly.
Because of these bugs, the planner_3d could create a path in which the robot collides with an obstacle in the following situation.
Assume that the cost of …
=>  planner_3d: fix cost calculation bug on in-place turning

costmap_cspace/include/costmap_cspace/costmap_3d_layer/base.h, costmap_cspace/include/costmap_cspace/costmap_3d_layer/footprint.h
Assume that there are 3 consecutive occupied grid cells on an `OccupancyGrid`, and `costmap_3d` expands these cells.
The black cells in the diagram above are the occupied cells, and the yellow, green, and red cells are expanded cells. 
The nearest occupied cell from the yellow cells is the left one, the nearest occupied cell from the green cells is the center one, and the nearest occupied cell from the red cell is the right one. Therefore, the expansion process for the left cell should be performed on the yellow cells, the process for the center cell on the green cells, and the process for the right cell on the red cells respectively.
By this PR, the expansion ranges are limited when adjacent cells have the same or larger costs than the expanding cell. Since occupied cells on the …
=> costmap_3d: avoid unnecessary grid expansions

planner_cspace/cfg/Planner3D.cfg, planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_dynamic_parameter_change.cpp
When `trigger_plan_by_costmap_update` option is true, `planner_3d` makes a new path soon after CSpace3DUpdate message is subscribed. 
With this option,  the updates of the costmap are reflected in path planning quickly.
=> planner_3d: add an option to trigger planning by costmap updates

planner_cspace/src/grid_astar_model_3dof.cpp
Turning penalties should not be added when the cost of a grid is less than `turn_penalty_cost_threshold_` on curved path primitives. This change does not affect the default behavior of planner_3d.
=> planner_3d: apply turn_penalty_cost_threshold in curve path

costmap_cspace/include/costmap_cspace/costmap_3d_layer/output.h, costmap_cspace/src/costmap_3d.cpp, costmap_cspace/test/src/test_costmap_3d.cpp, planner_cspace/test/src/test_planner_3d_map_size.cpp
`planner_3d` doesn't output node status when `costmap_update` is not published.
=> costmap_cspace: publish empty costmap_update on out-of-bound

planner_cspace/include/planner_cspace/planner_3d/grid_astar_model.h, planner_cspace/src/grid_astar_model_3dof.cpp, planner_cspace/src/planner_3d.cpp
When the parameters of planner_3D are changed using dynamic_reconfigure, the instance of GridAstarModel3D is always reconstructed. This makes the dynamic_reconfigure response time slow when the map is large.
This PR modifies the resetGridAstarModel() function to reconstruct the instance of GridAstarModel3D only when the map is changed or the `range_` parameter, which relates to the primal member variables in GridAstarModel3D, is updated.
=> planner_cspace: reconstuct GridAstarModel3D only when necessary

trajectory_tracker/src/trajectory_tracker.cpp, trajectory_tracker/test/include/trajectory_tracker_test.h, trajectory_tracker/test/src/test_trajectory_tracker.cpp, trajectory_tracker/test/src/test_trajectory_tracker_with_odom.cpp
The current method can cause large errors when the robot's coordinates are far from the origin and the ground is not flat. This PR fixes this problem and adds a corresponding test.
=> trajectory_tracker: fix the method for projecting paths onto 2D

planner_cspace/src/planner_3d.cpp, planner_cspace/test/src/test_navigate.cpp, planner_cspace/test/test/navigation_rostest.test
Don't output planner error status while temporary escaping with crowd escape mode.
=> planner_cspace: fix error status during crowd escape

planner_cspace/src/planner_3d.cpp
If the original goal cell cost is higher than the temporary goal select threshold, the goal wasn't rollback to the original goal even if it's reachable.
Fix goal rollback condition evaluation order.
=> planner_cspace: fix crowd escape to use original goal if reachable
